import{a as d,S as L,i as w}from"./assets/vendor-ad00ede7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S="/goit-js-hw-12/assets/error-80ee8afe.svg";d.defaults.baseURL="https://pixabay.com/api/";let y;const s={key:"41647148-76dbe9dab66bab2692c283b6e",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:1},k=new L(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:500}),f=document.querySelector(".gallery-form"),p=document.querySelector(".search-input"),m=document.querySelector(".gallery"),l=document.querySelector(".loader"),c=document.querySelector(".load-more-btn");f.addEventListener("submit",async t=>{if(t.preventDefault(),!p.value.trim()){u("Please fill in the search field");return}try{m.innerHTML="",l.style.display="inline-block",s.q=p.value.trim(),s.page=1;const o=await g();y=o.totalHits,h(o)}catch(o){console.log(o)}});c.addEventListener("click",async()=>{try{l.style.display="inline-block";const t=await g();h(t)}catch(t){console.log(t)}});async function g(){return(await d.get("",{params:s})).data}function h(t){if(!t.total){u("Sorry, there are no images matching your search query. Please, try again!"),l.style.display="none";return}const o=t.hits.map(({largeImageURL:i,webformatURL:n,tags:e,likes:r,views:a,comments:b,downloads:v})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="api-img" src="${n}" alt="${e}">
            <div class="img-desc">
              <span><b>Likes:</b> <br/>${r}</span>
              <span><b>Views:</b> <br/>${a}</span>
              <span><b>Comments:</b> <br/>${b}</span>
              <span><b>Downloads:</b> <br/>${v}</span>
            </div>
          </a>
        </li>
                  `).join("");m.insertAdjacentHTML("beforeend",o),l.style.display="none",q(),O(),k.refresh(),f.reset()}function q(){Math.ceil(y/s.per_page)===s.page?(u("We're sorry, but you've reached the end of search results."),c.style.display="none"):(s.page+=1,c.style.display="inline-block")}function O(){if(s.page>1){const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}}function u(t){w.show({position:"topRight",iconUrl:S,message:t,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",close:!1,closeOnClick:!0,closeOnEscape:!0})}
//# sourceMappingURL=commonHelpers2.js.map
